name: lite_vision_ai
description: "A lightweight and elegant Flutter library for TensorFlow Lite image classification."
version: 1.0.1
homepage: https://github.com/anas-saad/lite_vision_ai

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.12.1
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
